// Licensed to Elasticsearch B.V. under one or more agreements.
// Elasticsearch B.V. licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type BuildManifest struct {
	ID                            int64
	IntegrationID                 sql.NullInt64
	DependenciesEcsReference      sql.NullString
	DependenciesEcsImportMappings sql.NullBool
	FilePath                      string
}

type Change struct {
	ID          int64
	ReleaseID   sql.NullInt64
	Description sql.NullString
	Type        sql.NullString
	Link        sql.NullString
	FilePath    string
	LineNumber  sql.NullInt64
	Col         sql.NullInt64
}

type Changelog struct {
	ID            int64
	IntegrationID sql.NullInt64
	FilePath      string
}

type DataStream struct {
	ID                                           int64
	IntegrationID                                int64
	Name                                         string
	Dataset                                      sql.NullString
	DatasetIsPrefix                              sql.NullBool
	IlmPolicy                                    sql.NullString
	Release                                      sql.NullString
	Title                                        string
	Type                                         sql.NullString
	ElasticsearchIndexMode                       sql.NullString
	ElasticsearchSourceMode                      sql.NullString
	ElasticsearchDynamicDataset                  sql.NullBool
	ElasticsearchDynamicNamespace                sql.NullBool
	ElasticsearchPrivilegesProperties            sql.NullString
	ElasticsearchIndexTemplateSettings           sql.NullString
	ElasticsearchIndexTemplateMappings           sql.NullString
	ElasticsearchIndexTemplateIngestPipelineName sql.NullString
	ElasticsearchIndexTemplateDataStreamHidden   sql.NullBool
	FilePath                                     string
}

type DataStreamField struct {
	DataStreamID   int64
	FieldID        int64
	FieldsFileName string
}

type DiscoveryField struct {
	ID            int64
	IntegrationID sql.NullInt64
	Name          sql.NullString
}

type Field struct {
	ID              int64
	Name            string
	Type            sql.NullString
	Description     sql.NullString
	Value           sql.NullString
	Example         sql.NullString
	Pattern         sql.NullString
	DateFormat      sql.NullString
	Analyzer        sql.NullString
	SearchAnalyzer  sql.NullString
	IgnoreAbove     sql.NullInt64
	MultiFields     sql.NullString
	Enabled         sql.NullBool
	Dynamic         sql.NullString
	Indexed         sql.NullBool
	DocValues       sql.NullBool
	CopyTo          sql.NullString
	ScalingFactor   sql.NullInt64
	AliasTargetPath sql.NullString
	Normalize       sql.NullString
	Normalizer      sql.NullString
	NullValue       sql.NullString
	Dimension       sql.NullBool
	MetricType      sql.NullString
	Unit            sql.NullString
	External        sql.NullString
	YamlPath        sql.NullString
	FilePath        string
	LineNumber      int64
	Col             int64
}

type IngestPipeline struct {
	ID           int64
	DataStreamID sql.NullInt64
	Name         sql.NullString
	Description  sql.NullString
	Version      sql.NullInt64
	Meta         sql.NullString
	FilePath     string
}

type Integration struct {
	ID                             int64
	Name                           string
	DirName                        string
	Title                          string
	Version                        string
	Description                    string
	Type                           string
	FormatVersion                  string
	License                        sql.NullString
	Release                        sql.NullString
	PolicyTemplatesBehavior        sql.NullString
	ConditionsElasticSubscription  sql.NullString
	ConditionsKibanaVersion        sql.NullString
	SourceLicense                  sql.NullString
	OwnerGithub                    string
	OwnerType                      string
	ElasticsearchPrivilegesCluster sql.NullString
	AgentPrivilegesRoot            sql.NullBool
	FilePath                       string
}

type IntegrationCategory struct {
	IntegrationID int64
	Category      string
}

type IntegrationIcon struct {
	ID            int64
	IntegrationID sql.NullInt64
	Src           sql.NullString
	Title         sql.NullString
	Size          sql.NullString
	Type          sql.NullString
	DarkMode      sql.NullBool
}

type IntegrationScreenshot struct {
	ID            int64
	IntegrationID sql.NullInt64
	Src           sql.NullString
	Title         sql.NullString
	Size          sql.NullString
	Type          sql.NullString
}

type IntegrationVar struct {
	IntegrationID int64
	VarID         int64
}

type PolicyTemplate struct {
	ID                                              int64
	IntegrationID                                   int64
	Name                                            string
	Title                                           string
	Description                                     string
	Type                                            sql.NullString
	Input                                           sql.NullString
	TemplatePath                                    sql.NullString
	Multiple                                        sql.NullBool
	FipsCompatible                                  sql.NullBool
	DeploymentModesDefaultEnabled                   sql.NullBool
	DeploymentModesAgentlessEnabled                 sql.NullBool
	DeploymentModesAgentlessIsDefault               sql.NullBool
	DeploymentModesAgentlessOrganization            sql.NullString
	DeploymentModesAgentlessDivision                sql.NullString
	DeploymentModesAgentlessTeam                    sql.NullString
	DeploymentModesAgentlessResourcesRequestsMemory sql.NullString
	DeploymentModesAgentlessResourcesRequestsCpu    sql.NullString
}

type PolicyTemplateCategory struct {
	PolicyTemplateID int64
	Category         string
}

type PolicyTemplateDataStream struct {
	PolicyTemplateID sql.NullInt64
	DataStreamName   sql.NullString
}

type PolicyTemplateIcon struct {
	ID               int64
	PolicyTemplateID sql.NullInt64
	Src              sql.NullString
	Title            sql.NullString
	Size             sql.NullString
	Type             sql.NullString
	DarkMode         sql.NullBool
}

type PolicyTemplateInput struct {
	ID               int64
	PolicyTemplateID int64
	Type             string
	Title            string
	Description      string
	InputGroup       sql.NullString
	TemplatePath     sql.NullString
	Multi            sql.NullBool
}

type PolicyTemplateInputVar struct {
	PolicyTemplateInputID int64
	VarID                 int64
}

type PolicyTemplateScreenshot struct {
	ID               int64
	PolicyTemplateID sql.NullInt64
	Src              sql.NullString
	Title            sql.NullString
	Size             sql.NullString
	Type             sql.NullString
}

type PolicyTemplateVar struct {
	PolicyTemplateID int64
	VarID            int64
}

type Release struct {
	ID          int64
	ChangelogID sql.NullInt64
	Version     sql.NullString
	FilePath    string
	LineNumber  sql.NullInt64
	Col         sql.NullInt64
}

type SampleEvent struct {
	ID           int64
	DataStreamID sql.NullInt64
	Event        sql.NullString
	FilePath     string
}

type Stream struct {
	ID           int64
	DataStreamID int64
	Input        string
	Description  string
	Title        string
	TemplatePath sql.NullString
	Enabled      sql.NullBool
}

type StreamVar struct {
	StreamID int64
	VarID    int64
}

type Transform struct {
	ID                                       int64
	IntegrationID                            int64
	Name                                     string
	TransformSourceIndex                     string
	TransformSourceQuery                     sql.NullString
	TransformSourceRuntimeMappings           sql.NullString
	TransformDestIndex                       string
	TransformDestPipeline                    sql.NullString
	TransformDestAliasesJson                 sql.NullString
	TransformPivotGroupBy                    sql.NullString
	TransformPivotAggregations               sql.NullString
	TransformPivotAggs                       sql.NullString
	TransformLatestSort                      sql.NullString
	TransformLatestUniqueKey                 sql.NullString
	TransformDescription                     sql.NullString
	TransformFrequency                       sql.NullString
	TransformSettingsDatesAsEpochMillis      sql.NullBool
	TransformSettingsDocsPerSecond           sql.NullFloat64
	TransformSettingsAlignCheckpoints        sql.NullBool
	TransformSettingsMaxPageSearchSize       sql.NullInt64
	TransformSettingsUsePointInTime          sql.NullBool
	TransformSettingsDeduceMappings          sql.NullBool
	TransformSettingsUnattended              sql.NullBool
	TransformMeta                            sql.NullString
	TransformRetentionPolicyTimeField        sql.NullString
	TransformRetentionPolicyTimeMaxAge       sql.NullString
	TransformSyncTimeField                   sql.NullString
	TransformSyncTimeDelay                   sql.NullString
	ManifestDestinationIndexTemplateMappings sql.NullString
	ManifestDestinationIndexTemplateSettings sql.NullString
	ManifestStart                            sql.NullBool
	FilePath                                 string
}

type TransformDestAlias struct {
	ID             int64
	TransformID    sql.NullInt64
	Alias          sql.NullString
	MoveOnCreation sql.NullBool
}

type TransformField struct {
	TransformID int64
	FieldID     int64
}

type Var struct {
	ID                    int64
	Name                  string
	DefaultValue          sql.NullString
	Description           sql.NullString
	Type                  string
	Title                 sql.NullString
	Multi                 sql.NullBool
	Required              sql.NullBool
	Secret                sql.NullBool
	ShowUser              sql.NullBool
	HideInDeploymentModes sql.NullString
	FilePath              string
	LineNumber            int64
	Col                   int64
}

type VarOption struct {
	ID    int64
	VarID sql.NullInt64
	Value sql.NullString
	Text  sql.NullString
}
