// Licensed to Elasticsearch B.V. under one or more agreements.
// Elasticsearch B.V. licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const insertBuildManifest = `-- name: InsertBuildManifest :one
INSERT INTO build_manifests (integration_id, dependencies_ecs_reference,
                              dependencies_ecs_import_mappings, file_path)
VALUES (?, ?, ?, ?) RETURNING id
`

type InsertBuildManifestParams struct {
	IntegrationID                 int64
	DependenciesEcsReference      sql.NullString
	DependenciesEcsImportMappings sql.NullBool
	FilePath                      string
}

func (q *Queries) InsertBuildManifest(ctx context.Context, arg InsertBuildManifestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBuildManifest,
		arg.IntegrationID,
		arg.DependenciesEcsReference,
		arg.DependenciesEcsImportMappings,
		arg.FilePath,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChange = `-- name: InsertChange :one
INSERT INTO changes (release_id, description, type, link, file_path,
                     line_number, col)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertChangeParams struct {
	ReleaseID   int64
	Description sql.NullString
	Type        sql.NullString
	Link        sql.NullString
	FilePath    string
	LineNumber  sql.NullInt64
	Col         sql.NullInt64
}

func (q *Queries) InsertChange(ctx context.Context, arg InsertChangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChange,
		arg.ReleaseID,
		arg.Description,
		arg.Type,
		arg.Link,
		arg.FilePath,
		arg.LineNumber,
		arg.Col,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChangelog = `-- name: InsertChangelog :one
INSERT INTO changelogs (integration_id, file_path)
VALUES (?, ?) RETURNING id
`

type InsertChangelogParams struct {
	IntegrationID int64
	FilePath      string
}

func (q *Queries) InsertChangelog(ctx context.Context, arg InsertChangelogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChangelog, arg.IntegrationID, arg.FilePath)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDataStream = `-- name: InsertDataStream :one
INSERT INTO data_streams (integration_id, name, dataset, dataset_is_prefix,
                          ilm_policy, release, title, type,
                          elasticsearch_index_mode, elasticsearch_source_mode,
                          elasticsearch_dynamic_dataset,
                          elasticsearch_dynamic_namespace,
                          elasticsearch_privileges_properties,
                          elasticsearch_index_template_settings,
                          elasticsearch_index_template_mappings,
                          elasticsearch_index_template_ingest_pipeline_name,
                          elasticsearch_index_template_data_stream_hidden,
                          file_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertDataStreamParams struct {
	IntegrationID                                int64
	Name                                         string
	Dataset                                      sql.NullString
	DatasetIsPrefix                              sql.NullBool
	IlmPolicy                                    sql.NullString
	Release                                      sql.NullString
	Title                                        string
	Type                                         sql.NullString
	ElasticsearchIndexMode                       sql.NullString
	ElasticsearchSourceMode                      sql.NullString
	ElasticsearchDynamicDataset                  sql.NullBool
	ElasticsearchDynamicNamespace                sql.NullBool
	ElasticsearchPrivilegesProperties            sql.NullString
	ElasticsearchIndexTemplateSettings           sql.NullString
	ElasticsearchIndexTemplateMappings           sql.NullString
	ElasticsearchIndexTemplateIngestPipelineName sql.NullString
	ElasticsearchIndexTemplateDataStreamHidden   sql.NullBool
	FilePath                                     string
}

func (q *Queries) InsertDataStream(ctx context.Context, arg InsertDataStreamParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDataStream,
		arg.IntegrationID,
		arg.Name,
		arg.Dataset,
		arg.DatasetIsPrefix,
		arg.IlmPolicy,
		arg.Release,
		arg.Title,
		arg.Type,
		arg.ElasticsearchIndexMode,
		arg.ElasticsearchSourceMode,
		arg.ElasticsearchDynamicDataset,
		arg.ElasticsearchDynamicNamespace,
		arg.ElasticsearchPrivilegesProperties,
		arg.ElasticsearchIndexTemplateSettings,
		arg.ElasticsearchIndexTemplateMappings,
		arg.ElasticsearchIndexTemplateIngestPipelineName,
		arg.ElasticsearchIndexTemplateDataStreamHidden,
		arg.FilePath,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDataStreamField = `-- name: InsertDataStreamField :exec
INSERT INTO data_stream_fields (data_stream_id, field_id, fields_file_name)
VALUES (?, ?, ?)
`

type InsertDataStreamFieldParams struct {
	DataStreamID   int64
	FieldID        int64
	FieldsFileName string
}

func (q *Queries) InsertDataStreamField(ctx context.Context, arg InsertDataStreamFieldParams) error {
	_, err := q.db.ExecContext(ctx, insertDataStreamField, arg.DataStreamID, arg.FieldID, arg.FieldsFileName)
	return err
}

const insertDiscoveryField = `-- name: InsertDiscoveryField :one
INSERT INTO discovery_fields (integration_id, name)
VALUES (?, ?) RETURNING id
`

type InsertDiscoveryFieldParams struct {
	IntegrationID int64
	Name          sql.NullString
}

func (q *Queries) InsertDiscoveryField(ctx context.Context, arg InsertDiscoveryFieldParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDiscoveryField, arg.IntegrationID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertField = `-- name: InsertField :one
INSERT INTO fields (name, type, description, value, example, pattern,
                    date_format,
                    analyzer, search_analyzer,
                    ignore_above, multi_fields, enabled, dynamic, indexed,
                    doc_values, copy_to, scaling_factor, alias_target_path,
                    normalize, normalizer, null_value,
                    dimension, metric_type, external, unresolvable,
                    yaml_path, file_path, line_number, col)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?) RETURNING id
`

type InsertFieldParams struct {
	Name            string
	Type            sql.NullString
	Description     sql.NullString
	Value           sql.NullString
	Example         sql.NullString
	Pattern         sql.NullString
	DateFormat      sql.NullString
	Analyzer        sql.NullString
	SearchAnalyzer  sql.NullString
	IgnoreAbove     sql.NullInt64
	MultiFields     sql.NullString
	Enabled         sql.NullBool
	Dynamic         sql.NullString
	Indexed         sql.NullBool
	DocValues       sql.NullBool
	CopyTo          sql.NullString
	ScalingFactor   sql.NullInt64
	AliasTargetPath sql.NullString
	Normalize       sql.NullString
	Normalizer      sql.NullString
	NullValue       sql.NullString
	Dimension       sql.NullBool
	MetricType      sql.NullString
	External        sql.NullString
	Unresolvable    sql.NullInt64
	YamlPath        sql.NullString
	FilePath        string
	LineNumber      int64
	Col             int64
}

func (q *Queries) InsertField(ctx context.Context, arg InsertFieldParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertField,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.Value,
		arg.Example,
		arg.Pattern,
		arg.DateFormat,
		arg.Analyzer,
		arg.SearchAnalyzer,
		arg.IgnoreAbove,
		arg.MultiFields,
		arg.Enabled,
		arg.Dynamic,
		arg.Indexed,
		arg.DocValues,
		arg.CopyTo,
		arg.ScalingFactor,
		arg.AliasTargetPath,
		arg.Normalize,
		arg.Normalizer,
		arg.NullValue,
		arg.Dimension,
		arg.MetricType,
		arg.External,
		arg.Unresolvable,
		arg.YamlPath,
		arg.FilePath,
		arg.LineNumber,
		arg.Col,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIngestPipeline = `-- name: InsertIngestPipeline :one
INSERT INTO ingest_pipelines (data_stream_id, name, description, version, meta,
                               file_path)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertIngestPipelineParams struct {
	DataStreamID int64
	Name         sql.NullString
	Description  sql.NullString
	Version      sql.NullInt64
	Meta         sql.NullString
	FilePath     string
}

func (q *Queries) InsertIngestPipeline(ctx context.Context, arg InsertIngestPipelineParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertIngestPipeline,
		arg.DataStreamID,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.Meta,
		arg.FilePath,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIngestProcessor = `-- name: InsertIngestProcessor :one
INSERT INTO ingest_processors (ingest_pipeline_id, type, attributes, json_pointer,
                                file_path, line_number, col)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertIngestProcessorParams struct {
	IngestPipelineID int64
	Type             string
	Attributes       interface{}
	JsonPointer      string
	FilePath         string
	LineNumber       int64
	Col              int64
}

func (q *Queries) InsertIngestProcessor(ctx context.Context, arg InsertIngestProcessorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertIngestProcessor,
		arg.IngestPipelineID,
		arg.Type,
		arg.Attributes,
		arg.JsonPointer,
		arg.FilePath,
		arg.LineNumber,
		arg.Col,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIntegration = `-- name: InsertIntegration :one
INSERT INTO integrations (name, dir_name, title, version, description, type,
                          format_version, license, release,
                          policy_templates_behavior,
                          conditions_elastic_subscription,
                          conditions_kibana_version, source_license,
                          owner_github, owner_type,
                          elasticsearch_privileges_cluster,
                          agent_privileges_root,
                          file_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
        ?, ?) RETURNING id
`

type InsertIntegrationParams struct {
	Name                           string
	DirName                        string
	Title                          string
	Version                        string
	Description                    string
	Type                           string
	FormatVersion                  string
	License                        sql.NullString
	Release                        sql.NullString
	PolicyTemplatesBehavior        sql.NullString
	ConditionsElasticSubscription  sql.NullString
	ConditionsKibanaVersion        sql.NullString
	SourceLicense                  sql.NullString
	OwnerGithub                    string
	OwnerType                      string
	ElasticsearchPrivilegesCluster sql.NullString
	AgentPrivilegesRoot            sql.NullBool
	FilePath                       string
}

func (q *Queries) InsertIntegration(ctx context.Context, arg InsertIntegrationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertIntegration,
		arg.Name,
		arg.DirName,
		arg.Title,
		arg.Version,
		arg.Description,
		arg.Type,
		arg.FormatVersion,
		arg.License,
		arg.Release,
		arg.PolicyTemplatesBehavior,
		arg.ConditionsElasticSubscription,
		arg.ConditionsKibanaVersion,
		arg.SourceLicense,
		arg.OwnerGithub,
		arg.OwnerType,
		arg.ElasticsearchPrivilegesCluster,
		arg.AgentPrivilegesRoot,
		arg.FilePath,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIntegrationCategory = `-- name: InsertIntegrationCategory :exec
INSERT INTO integration_categories (integration_id, category)
VALUES (?, ?)
`

type InsertIntegrationCategoryParams struct {
	IntegrationID int64
	Category      string
}

func (q *Queries) InsertIntegrationCategory(ctx context.Context, arg InsertIntegrationCategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertIntegrationCategory, arg.IntegrationID, arg.Category)
	return err
}

const insertIntegrationIcon = `-- name: InsertIntegrationIcon :one
INSERT INTO integration_icons (integration_id, src, title, size, type, dark_mode)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertIntegrationIconParams struct {
	IntegrationID int64
	Src           sql.NullString
	Title         sql.NullString
	Size          sql.NullString
	Type          sql.NullString
	DarkMode      sql.NullBool
}

func (q *Queries) InsertIntegrationIcon(ctx context.Context, arg InsertIntegrationIconParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertIntegrationIcon,
		arg.IntegrationID,
		arg.Src,
		arg.Title,
		arg.Size,
		arg.Type,
		arg.DarkMode,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIntegrationScreenshot = `-- name: InsertIntegrationScreenshot :one
INSERT INTO integration_screenshots (integration_id, src, title, size, type, width, height, byte_size)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertIntegrationScreenshotParams struct {
	IntegrationID int64
	Src           sql.NullString
	Title         sql.NullString
	Size          sql.NullString
	Type          sql.NullString
	Width         sql.NullInt64
	Height        sql.NullInt64
	ByteSize      sql.NullInt64
}

func (q *Queries) InsertIntegrationScreenshot(ctx context.Context, arg InsertIntegrationScreenshotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertIntegrationScreenshot,
		arg.IntegrationID,
		arg.Src,
		arg.Title,
		arg.Size,
		arg.Type,
		arg.Width,
		arg.Height,
		arg.ByteSize,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIntegrationVar = `-- name: InsertIntegrationVar :exec
INSERT INTO integration_vars (integration_id, var_id)
VALUES (?, ?)
`

type InsertIntegrationVarParams struct {
	IntegrationID int64
	VarID         int64
}

func (q *Queries) InsertIntegrationVar(ctx context.Context, arg InsertIntegrationVarParams) error {
	_, err := q.db.ExecContext(ctx, insertIntegrationVar, arg.IntegrationID, arg.VarID)
	return err
}

const insertPolicyTemplate = `-- name: InsertPolicyTemplate :one
INSERT INTO policy_templates (integration_id, name, title, description, type,
                              deployment_modes_default_enabled,
                              deployment_modes_agentless_enabled,
                              deployment_modes_agentless_is_default,
                              deployment_modes_agentless_organization,
                              deployment_modes_agentless_division,
                              deployment_modes_agentless_team,
                              deployment_modes_agentless_resources_requests_memory,
                              deployment_modes_agentless_resources_requests_cpu)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertPolicyTemplateParams struct {
	IntegrationID                                   int64
	Name                                            string
	Title                                           string
	Description                                     string
	Type                                            sql.NullString
	DeploymentModesDefaultEnabled                   sql.NullBool
	DeploymentModesAgentlessEnabled                 sql.NullBool
	DeploymentModesAgentlessIsDefault               sql.NullBool
	DeploymentModesAgentlessOrganization            sql.NullString
	DeploymentModesAgentlessDivision                sql.NullString
	DeploymentModesAgentlessTeam                    sql.NullString
	DeploymentModesAgentlessResourcesRequestsMemory sql.NullString
	DeploymentModesAgentlessResourcesRequestsCpu    sql.NullString
}

func (q *Queries) InsertPolicyTemplate(ctx context.Context, arg InsertPolicyTemplateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplate,
		arg.IntegrationID,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.DeploymentModesDefaultEnabled,
		arg.DeploymentModesAgentlessEnabled,
		arg.DeploymentModesAgentlessIsDefault,
		arg.DeploymentModesAgentlessOrganization,
		arg.DeploymentModesAgentlessDivision,
		arg.DeploymentModesAgentlessTeam,
		arg.DeploymentModesAgentlessResourcesRequestsMemory,
		arg.DeploymentModesAgentlessResourcesRequestsCpu,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateCategory = `-- name: InsertPolicyTemplateCategory :exec
INSERT INTO policy_template_categories (policy_template_id, category)
VALUES (?, ?)
`

type InsertPolicyTemplateCategoryParams struct {
	PolicyTemplateID int64
	Category         string
}

func (q *Queries) InsertPolicyTemplateCategory(ctx context.Context, arg InsertPolicyTemplateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertPolicyTemplateCategory, arg.PolicyTemplateID, arg.Category)
	return err
}

const insertPolicyTemplateDataStream = `-- name: InsertPolicyTemplateDataStream :exec
INSERT INTO policy_template_data_streams (policy_template_id, data_stream_name)
VALUES (?, ?)
`

type InsertPolicyTemplateDataStreamParams struct {
	PolicyTemplateID int64
	DataStreamName   string
}

func (q *Queries) InsertPolicyTemplateDataStream(ctx context.Context, arg InsertPolicyTemplateDataStreamParams) error {
	_, err := q.db.ExecContext(ctx, insertPolicyTemplateDataStream, arg.PolicyTemplateID, arg.DataStreamName)
	return err
}

const insertPolicyTemplateIcon = `-- name: InsertPolicyTemplateIcon :one
INSERT INTO policy_template_icons (policy_template_id, src, title, size, type, dark_mode)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertPolicyTemplateIconParams struct {
	PolicyTemplateID int64
	Src              sql.NullString
	Title            sql.NullString
	Size             sql.NullString
	Type             sql.NullString
	DarkMode         sql.NullBool
}

func (q *Queries) InsertPolicyTemplateIcon(ctx context.Context, arg InsertPolicyTemplateIconParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateIcon,
		arg.PolicyTemplateID,
		arg.Src,
		arg.Title,
		arg.Size,
		arg.Type,
		arg.DarkMode,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateInput = `-- name: InsertPolicyTemplateInput :one
INSERT INTO policy_template_inputs (policy_template_id, type, title,
                                    description,
                                    input_group, template_path, multi)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertPolicyTemplateInputParams struct {
	PolicyTemplateID int64
	Type             string
	Title            string
	Description      string
	InputGroup       sql.NullString
	TemplatePath     sql.NullString
	Multi            sql.NullBool
}

func (q *Queries) InsertPolicyTemplateInput(ctx context.Context, arg InsertPolicyTemplateInputParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateInput,
		arg.PolicyTemplateID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.InputGroup,
		arg.TemplatePath,
		arg.Multi,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateInputVars = `-- name: InsertPolicyTemplateInputVars :exec
INSERT INTO policy_template_input_vars (policy_template_input_id, var_id)
VALUES (?, ?)
`

type InsertPolicyTemplateInputVarsParams struct {
	PolicyTemplateInputID int64
	VarID                 int64
}

func (q *Queries) InsertPolicyTemplateInputVars(ctx context.Context, arg InsertPolicyTemplateInputVarsParams) error {
	_, err := q.db.ExecContext(ctx, insertPolicyTemplateInputVars, arg.PolicyTemplateInputID, arg.VarID)
	return err
}

const insertPolicyTemplateScreenshot = `-- name: InsertPolicyTemplateScreenshot :one
INSERT INTO policy_template_screenshots (policy_template_id, src, title, size, type, width, height, byte_size)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertPolicyTemplateScreenshotParams struct {
	PolicyTemplateID int64
	Src              sql.NullString
	Title            sql.NullString
	Size             sql.NullString
	Type             sql.NullString
	Width            sql.NullInt64
	Height           sql.NullInt64
	ByteSize         sql.NullInt64
}

func (q *Queries) InsertPolicyTemplateScreenshot(ctx context.Context, arg InsertPolicyTemplateScreenshotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPolicyTemplateScreenshot,
		arg.PolicyTemplateID,
		arg.Src,
		arg.Title,
		arg.Size,
		arg.Type,
		arg.Width,
		arg.Height,
		arg.ByteSize,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPolicyTemplateVar = `-- name: InsertPolicyTemplateVar :exec
INSERT INTO policy_template_vars (policy_template_id, var_id)
VALUES (?, ?)
`

type InsertPolicyTemplateVarParams struct {
	PolicyTemplateID int64
	VarID            int64
}

func (q *Queries) InsertPolicyTemplateVar(ctx context.Context, arg InsertPolicyTemplateVarParams) error {
	_, err := q.db.ExecContext(ctx, insertPolicyTemplateVar, arg.PolicyTemplateID, arg.VarID)
	return err
}

const insertRelease = `-- name: InsertRelease :one
INSERT INTO releases (changelog_id, version, file_path, line_number, col)
VALUES (?, ?, ?, ?, ?) RETURNING id
`

type InsertReleaseParams struct {
	ChangelogID int64
	Version     sql.NullString
	FilePath    string
	LineNumber  sql.NullInt64
	Col         sql.NullInt64
}

func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRelease,
		arg.ChangelogID,
		arg.Version,
		arg.FilePath,
		arg.LineNumber,
		arg.Col,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSampleEvent = `-- name: InsertSampleEvent :one
INSERT INTO sample_events (data_stream_id, event, file_path)
VALUES (?, ?, ?) RETURNING id
`

type InsertSampleEventParams struct {
	DataStreamID int64
	Event        sql.NullString
	FilePath     string
}

func (q *Queries) InsertSampleEvent(ctx context.Context, arg InsertSampleEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSampleEvent, arg.DataStreamID, arg.Event, arg.FilePath)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStream = `-- name: InsertStream :one
INSERT INTO streams (data_stream_id, input, description, title, template_path,
                     enabled)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertStreamParams struct {
	DataStreamID int64
	Input        string
	Description  string
	Title        string
	TemplatePath sql.NullString
	Enabled      sql.NullBool
}

func (q *Queries) InsertStream(ctx context.Context, arg InsertStreamParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertStream,
		arg.DataStreamID,
		arg.Input,
		arg.Description,
		arg.Title,
		arg.TemplatePath,
		arg.Enabled,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStreamVar = `-- name: InsertStreamVar :exec
INSERT INTO stream_vars (stream_id, var_id)
VALUES (?, ?)
`

type InsertStreamVarParams struct {
	StreamID int64
	VarID    int64
}

func (q *Queries) InsertStreamVar(ctx context.Context, arg InsertStreamVarParams) error {
	_, err := q.db.ExecContext(ctx, insertStreamVar, arg.StreamID, arg.VarID)
	return err
}

const insertTransform = `-- name: InsertTransform :one
INSERT INTO transforms (integration_id, name, transform_source_index,
                        transform_source_query,
                        transform_source_runtime_mappings, transform_dest_index,
                        transform_dest_pipeline,
                        transform_pivot_group_by, transform_pivot_aggregations,
                        transform_pivot_aggs,
                        transform_latest_sort, transform_latest_unique_key,
                        transform_description,
                        transform_frequency,
                        transform_settings_dates_as_epoch_millis,
                        transform_settings_docs_per_second,
                        transform_settings_align_checkpoints,
                        transform_settings_max_page_search_size,
                        transform_settings_use_point_in_time,
                        transform_settings_deduce_mappings,
                        transform_settings_unattended,
                        transform_meta, transform_retention_policy_time_field,
                        transform_retention_policy_time_max_age,
                        transform_sync_time_field,
                        transform_sync_time_delay,
                        manifest_destination_index_template_mappings,
                        manifest_destination_index_template_settings,
                        manifest_start, file_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertTransformParams struct {
	IntegrationID                            int64
	Name                                     string
	TransformSourceIndex                     string
	TransformSourceQuery                     sql.NullString
	TransformSourceRuntimeMappings           sql.NullString
	TransformDestIndex                       string
	TransformDestPipeline                    sql.NullString
	TransformPivotGroupBy                    sql.NullString
	TransformPivotAggregations               sql.NullString
	TransformPivotAggs                       sql.NullString
	TransformLatestSort                      sql.NullString
	TransformLatestUniqueKey                 sql.NullString
	TransformDescription                     sql.NullString
	TransformFrequency                       sql.NullString
	TransformSettingsDatesAsEpochMillis      sql.NullBool
	TransformSettingsDocsPerSecond           sql.NullFloat64
	TransformSettingsAlignCheckpoints        sql.NullBool
	TransformSettingsMaxPageSearchSize       sql.NullInt64
	TransformSettingsUsePointInTime          sql.NullBool
	TransformSettingsDeduceMappings          sql.NullBool
	TransformSettingsUnattended              sql.NullBool
	TransformMeta                            sql.NullString
	TransformRetentionPolicyTimeField        sql.NullString
	TransformRetentionPolicyTimeMaxAge       sql.NullString
	TransformSyncTimeField                   sql.NullString
	TransformSyncTimeDelay                   sql.NullString
	ManifestDestinationIndexTemplateMappings sql.NullString
	ManifestDestinationIndexTemplateSettings sql.NullString
	ManifestStart                            sql.NullBool
	FilePath                                 string
}

func (q *Queries) InsertTransform(ctx context.Context, arg InsertTransformParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTransform,
		arg.IntegrationID,
		arg.Name,
		arg.TransformSourceIndex,
		arg.TransformSourceQuery,
		arg.TransformSourceRuntimeMappings,
		arg.TransformDestIndex,
		arg.TransformDestPipeline,
		arg.TransformPivotGroupBy,
		arg.TransformPivotAggregations,
		arg.TransformPivotAggs,
		arg.TransformLatestSort,
		arg.TransformLatestUniqueKey,
		arg.TransformDescription,
		arg.TransformFrequency,
		arg.TransformSettingsDatesAsEpochMillis,
		arg.TransformSettingsDocsPerSecond,
		arg.TransformSettingsAlignCheckpoints,
		arg.TransformSettingsMaxPageSearchSize,
		arg.TransformSettingsUsePointInTime,
		arg.TransformSettingsDeduceMappings,
		arg.TransformSettingsUnattended,
		arg.TransformMeta,
		arg.TransformRetentionPolicyTimeField,
		arg.TransformRetentionPolicyTimeMaxAge,
		arg.TransformSyncTimeField,
		arg.TransformSyncTimeDelay,
		arg.ManifestDestinationIndexTemplateMappings,
		arg.ManifestDestinationIndexTemplateSettings,
		arg.ManifestStart,
		arg.FilePath,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTransformDestAlias = `-- name: InsertTransformDestAlias :one
INSERT INTO transform_dest_aliases (transform_id, alias, move_on_creation)
VALUES (?, ?, ?) RETURNING id
`

type InsertTransformDestAliasParams struct {
	TransformID    int64
	Alias          sql.NullString
	MoveOnCreation sql.NullBool
}

func (q *Queries) InsertTransformDestAlias(ctx context.Context, arg InsertTransformDestAliasParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTransformDestAlias, arg.TransformID, arg.Alias, arg.MoveOnCreation)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTransformField = `-- name: InsertTransformField :exec
INSERT INTO transform_fields (transform_id, field_id)
VALUES (?, ?)
`

type InsertTransformFieldParams struct {
	TransformID int64
	FieldID     int64
}

func (q *Queries) InsertTransformField(ctx context.Context, arg InsertTransformFieldParams) error {
	_, err := q.db.ExecContext(ctx, insertTransformField, arg.TransformID, arg.FieldID)
	return err
}

const insertVar = `-- name: InsertVar :one
INSERT INTO vars (name,
                  default_value,
                  description,
                  type,
                  title,
                  multi,
                  required,
                  secret,
                  show_user,
                  hide_in_deployment_modes,
                  file_path,
                  line_number,
                  col)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertVarParams struct {
	Name                  string
	DefaultValue          sql.NullString
	Description           sql.NullString
	Type                  string
	Title                 sql.NullString
	Multi                 sql.NullBool
	Required              sql.NullBool
	Secret                sql.NullBool
	ShowUser              sql.NullBool
	HideInDeploymentModes sql.NullString
	FilePath              string
	LineNumber            int64
	Col                   int64
}

func (q *Queries) InsertVar(ctx context.Context, arg InsertVarParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertVar,
		arg.Name,
		arg.DefaultValue,
		arg.Description,
		arg.Type,
		arg.Title,
		arg.Multi,
		arg.Required,
		arg.Secret,
		arg.ShowUser,
		arg.HideInDeploymentModes,
		arg.FilePath,
		arg.LineNumber,
		arg.Col,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertVarOption = `-- name: InsertVarOption :one
INSERT INTO var_options (var_id, value, text)
VALUES (?, ?, ?) RETURNING id
`

type InsertVarOptionParams struct {
	VarID int64
	Value sql.NullString
	Text  sql.NullString
}

func (q *Queries) InsertVarOption(ctx context.Context, arg InsertVarOptionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertVarOption, arg.VarID, arg.Value, arg.Text)
	var id int64
	err := row.Scan(&id)
	return id, err
}
