// Licensed to Elasticsearch B.V. under one or more agreements.
// Elasticsearch B.V. licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"regexp"
	"strings"
	"text/template"
)

type gentablesFlags struct {
	schema string
	out    string
}

var flags gentablesFlags

func init() {
	flag.StringVar(&flags.schema, "schema", "", "sql file containing 'CREATE TABLE' statements")
	flag.StringVar(&flags.out, "out", "", "output file name")
}

var (
	createTableRegex = regexp.MustCompile(`(?m)(?:-- .*\n)*CREATE TABLE (?:IF NOT EXISTS )?([\w_]+)[^;]+;`)

	funcMap = template.FuncMap{
		"backquote":      backquote,
		"lowerSnakeCase": upperSnakeCase,
	}

	tmpl = template.Must(
		template.New("tables.go").
			Funcs(funcMap).
			Option("missingkey=error").
			Parse(`
// Code generated by gentables.go. DO NOT EDIT.

package database
{{ range $t := .tables }}
const {{ lowerSnakeCase $t.Name }}TableStatement = {{ backquote $t.Statement }}
{{ end }}
var Creates = [...]string{
{{- range $t := .tables }}
	{{ lowerSnakeCase $t.Name }}TableStatement,
{{- end }}
}
`[1:]))
)

func main() {
	if err := Main(); err != nil {
		log.Fatal("ERROR:", err)
	}
}

func Main() error {
	flag.Parse()

	data, err := os.ReadFile(flags.schema)
	if err != nil {
		return err
	}

	type Table struct {
		Name, Statement string
	}
	var tables []Table
	for _, match := range createTableRegex.FindAllSubmatch(data, -1) {
		if len(match) != 2 {
			return fmt.Errorf("unexpected number of matches")
		}
		tables = append(tables, Table{string(match[1]), string(match[0])})
	}

	f, err := os.Create(flags.out)
	if err != nil {
		return fmt.Errorf("failed creating output file: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, map[string]any{"tables": tables})
}

func backquote(s string) (string, error) {
	if strings.ContainsRune(s, '`') {
		return "", fmt.Errorf("cannot backquote value containing a backtick: <%q>", s)
	}
	return "`" + s + "`", nil
}

func upperSnakeCase(s string) string {
	var sb strings.Builder
	parts := strings.Split(s, "_")
	for _, p := range parts {
		//nolint:staticcheck // It is deprecated, but it does the job for our table names.
		sb.WriteString(strings.Title(p))
	}
	return sb.String()
}
